### ISSUE TITLE
#ASKnet 2020/2021 Participants Should add their part of the stories to the respective files containing their names.

### ISSUE THREAD

**Issue by gibertgibs** [gibertgibs/-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021-#8]
Every participant is kindly requested to add their own parts of their story to the respective files containing their names in the code.
# THE STORY HINTS 
1. Brief life story as in childhood to status quo.
2. What transpired in your life to make you get started to see a way to change your community?
3. Your motivation as fars your vision is concerned.
3. What you hope to gain from this Training and how it will affect your community positively?
4. Your words of encouragement to your community people.
5. Conclusion
NB: Any suggestion to make the story lively is welcomed in the comment box.

**Comment by timmwille** [comment]
Not sure what you mean by the 1. one, can you explain a bit?

**Comment by gibertgibs** [comment]
Yeah. The no.1 Is a brief introduction  about who you are...Like I mean
your details. Personal details or backgrounds.

@Gilbips

**Comment by gibertgibs** [comment]
The status quo is your current situation.
1. Says briefly share your life story in your story. is from childhood and present situation in few words.

**Comment by wunbaai** [comment]
Can I know how to fork the respiratory?

**Comment by gibertgibs** [comment]
OKay first step is to go to the repository you wan to fork.
Where its written fork/the number of forkings written.
Click that word fork and it will lead you to to a couple of words.
Then scroll the screen to the left and you will get where to fork from at the last.

**Comment by wunbaai** [comment]
🆗

On Oct 23, 2020 12:08 AM, "Gilbert Charles" <notifications@github.com>
wrote:

OKay first step is to go to the repository you wan to fork.
Where its written fork/the number of forkings written.
Click that word fork and it will lead you to to a couple of words.
Then scroll the screen to the left and you will get where to fork from at
the last.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gibertgibs/-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021/issues/8#issuecomment-714763374>,
or unsubscribe
